from __future__ import annotations

from textwrap import dedent


def _loader_cell(model_id: str) -> str:
    """Build a task-independent loader.

    The generated code deliberately performs model inspection in the notebook
    runtime.  Inspecting a repo while the web page is generating a cell would
    make the page depend on server-side Transformers credentials and versions,
    and would also turn the selected task into an accidental loader hint.
    """
    return dedent(
        f'''
        # --- Cell 1: Model Loader (auto-generated by Claro.AI) ---
        # This cell only detects and loads the Hugging Face repo.
        import importlib
        import re
        import torch
        from transformers import AutoConfig

        MODEL_ID = {model_id!r}
        DEVICE = torch.device(
            "cuda" if torch.cuda.is_available()
            else "mps" if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available()
            else "cpu"
        )
        DTYPE = torch.float16 if DEVICE.type == "cuda" else torch.float32
        DEVICE_MAP = "auto" if DEVICE.type == "cuda" else None

        def _has_diffusers_model_index():
            try:
                from huggingface_hub import hf_hub_download
                hf_hub_download(MODEL_ID, "model_index.json")
                return True
            except Exception:
                return False

        _diffusers_repo = False
        _config_requires_remote_code = False

        # AutoConfig is the source of truth.  The order below is intentional:
        # auto_map -> architectures -> model_type -> encoder/decoder structure.
        try:
            config = AutoConfig.from_pretrained(MODEL_ID, trust_remote_code=False)
        except Exception:
            try:
                config = AutoConfig.from_pretrained(MODEL_ID, trust_remote_code=True)
                _config_requires_remote_code = True
            except Exception:
                # Pure Diffusers repos may not have a Transformers config at all.
                # Check model_index.json only after AutoConfig has failed.
                if not _has_diffusers_model_index():
                    raise
                _diffusers_repo = True
                config = type(
                    "_DiffusersConfig",
                    (),
                    {{
                        "auto_map": {{}},
                        "architectures": [],
                        "model_type": "",
                        "is_encoder_decoder": False,
                    }},
                )()
        auto_map = getattr(config, "auto_map", None) or {{}}
        architectures = list(getattr(config, "architectures", None) or [])
        model_type = str(getattr(config, "model_type", "") or "").lower()
        is_encoder_decoder = bool(getattr(config, "is_encoder_decoder", False))
        def _architecture_requires_remote_code():
            if _config_requires_remote_code or not auto_map:
                return _config_requires_remote_code
            transformers = importlib.import_module("transformers")
            mapped_targets = []
            for key, target in auto_map.items():
                if key.startswith("AutoModel"):
                    mapped_targets.extend(
                        target if isinstance(target, (list, tuple)) else [target]
                    )
            if not mapped_targets:
                mapped_targets = list(auto_map.values())
            return any(
                not hasattr(transformers, str(target).rsplit(".", 1)[-1])
                for target in mapped_targets
            )

        trust_remote_code = _architecture_requires_remote_code()

        def _auto_class_from_map():
            for key in auto_map:
                if key.startswith("AutoModelFor"):
                    return key
            return None

        def _auto_class_from_architecture():
            # These are head/interface suffixes, not a model-family list.
            # New families with conventional HF architecture names work here
            # without adding their model_type to Claro.AI.
            suffixes = (
                ("ForQuestionAnswering", "AutoModelForQuestionAnswering"),
                ("ForSequenceClassification", "AutoModelForSequenceClassification"),
                ("ForTokenClassification", "AutoModelForTokenClassification"),
                ("ForMultipleChoice", "AutoModelForMultipleChoice"),
                ("ForMaskedLM", "AutoModelForMaskedLM"),
                ("ForCausalLM", "AutoModelForCausalLM"),
                ("ForImageTextToText", "AutoModelForImageTextToText"),
                ("ForVision2Seq", "AutoModelForVision2Seq"),
                ("ForSpeechSeq2Seq", "AutoModelForSpeechSeq2Seq"),
                ("ForAudioClassification", "AutoModelForAudioClassification"),
                ("ForImageClassification", "AutoModelForImageClassification"),
                ("ForObjectDetection", "AutoModelForObjectDetection"),
                ("ForSemanticSegmentation", "AutoModelForSemanticSegmentation"),
                ("ForDepthEstimation", "AutoModelForDepthEstimation"),
                ("ForCTC", "AutoModelForCTC"),
            )
            for architecture in architectures:
                for suffix, auto_class in suffixes:
                    if architecture.endswith(suffix):
                        return auto_class
            return None

        def _is_multimodal():
            metadata = " ".join(
                str(getattr(config, name, "") or "")
                for name in ("processor_class", "image_processor_type", "feature_extractor_type")
            ).lower()
            names = " ".join(architectures).lower() + " " + model_type
            return any(
                marker in metadata + " " + names
                for marker in ("vision", "image", "ocr", "document", "llava", "pix2struct")
            )

        def _is_audio():
            metadata = " ".join(
                str(getattr(config, name, "") or "")
                for name in ("processor_class", "feature_extractor_type")
            ).lower()
            names = " ".join(architectures).lower() + " " + model_type
            return any(marker in metadata + " " + names for marker in ("audio", "speech", "whisper"))

        def _auto_class_from_model_type():
            # model_type is a narrow fallback for families whose architecture
            # metadata is missing.  It is deliberately interface-oriented,
            # not a list of every model family on the Hub.
            return {{
                "whisper": "AutoModelForSpeechSeq2Seq",
                "wav2vec2": "AutoModelForCTC",
                "hubert": "AutoModelForCTC",
                "donut": "AutoModelForVision2Seq",
                "vision-encoder-decoder": "AutoModelForVision2Seq",
            }}.get(model_type)

        # Diffusers repos do not have a Transformers AutoModel.  Detection is
        # repo-based rather than task-based, so text-to-image and future
        # Diffusers tasks use the same loader cell.
        if _diffusers_repo:
            from diffusers import DiffusionPipeline

            pipe_kwargs = {{"torch_dtype": DTYPE}} if DEVICE.type == "cuda" else {{}}
            pipe = DiffusionPipeline.from_pretrained(MODEL_ID, **pipe_kwargs)
            pipe = pipe.to(DEVICE)
            model = None
            tokenizer = None
            processor = None
            feature_extractor = None
            loaded_class = "DiffusionPipeline"
        else:
            mapped_class = _auto_class_from_map()
            architecture_class = _auto_class_from_architecture()
            model_type_class = _auto_class_from_model_type()
            loaded_class = mapped_class or architecture_class or model_type_class

            known_text_decoder_types = {{
                "llama", "qwen", "qwen2", "gemma", "gemma2", "mistral",
                "mixtral", "deepseek", "phi", "phi3", "gpt2", "gpt_neox",
                "falcon", "bloom", "mamba", "starcoder",
            }}
            if not loaded_class:
                if is_encoder_decoder:
                    loaded_class = "AutoModelForSeq2SeqLM"
                elif _is_multimodal():
                    loaded_class = "AutoModelForVision2Seq"
                elif model_type in known_text_decoder_types:
                    loaded_class = "AutoModelForCausalLM"
                else:
                    loaded_class = "AutoModel"
                    print(
                        f"Warning: unknown architecture for {{MODEL_ID}}; "
                        "using AutoModel."
                    )
            elif loaded_class == "AutoModelForConditionalGeneration":
                loaded_class = (
                    "AutoModelForVision2Seq" if _is_multimodal()
                    else "AutoModelForSeq2SeqLM" if is_encoder_decoder
                    else "AutoModelForCausalLM"
                )

            transformers = importlib.import_module("transformers")
            ModelClass = getattr(transformers, loaded_class, None)
            if ModelClass is None and loaded_class == "AutoModelForImageTextToText":
                ModelClass = getattr(transformers, "AutoModelForVision2Seq")
                loaded_class = "AutoModelForVision2Seq"
            if ModelClass is None:
                raise RuntimeError(
                    f"Transformers does not provide {{loaded_class}} for {{MODEL_ID}}. "
                    f"architectures={{architectures!r}}, model_type={{model_type!r}}"
                )

            model_kwargs = {{"trust_remote_code": trust_remote_code}}
            if DEVICE.type == "cuda":
                model_kwargs.update(torch_dtype=DTYPE, device_map=DEVICE_MAP)
            model = ModelClass.from_pretrained(MODEL_ID, **model_kwargs)
            if DEVICE_MAP is None:
                model = model.to(DEVICE)
            model.eval()

            # Processor choice comes from repo/config metadata, never from the
            # selected pipeline task.
            tokenizer = None
            processor = None
            feature_extractor = None
            if any(
                marker in loaded_class
                for marker in (
                    "ImageClassification",
                    "ObjectDetection",
                    "SemanticSegmentation",
                    "DepthEstimation",
                )
            ):
                from transformers import AutoImageProcessor
                processor = AutoImageProcessor.from_pretrained(
                    MODEL_ID, trust_remote_code=trust_remote_code
                )
            elif _is_multimodal() or "Vision2Seq" in loaded_class or "ImageTextToText" in loaded_class:
                from transformers import AutoProcessor
                processor = AutoProcessor.from_pretrained(
                    MODEL_ID, trust_remote_code=trust_remote_code
                )
            elif _is_audio() and "AudioClassification" in loaded_class:
                from transformers import AutoFeatureExtractor
                feature_extractor = AutoFeatureExtractor.from_pretrained(
                    MODEL_ID, trust_remote_code=trust_remote_code
                )
                processor = feature_extractor
            elif _is_audio() or "SpeechSeq2Seq" in loaded_class or "CTC" in loaded_class:
                from transformers import AutoProcessor
                processor = AutoProcessor.from_pretrained(
                    MODEL_ID, trust_remote_code=trust_remote_code
                )
            else:
                from transformers import AutoTokenizer
                tokenizer = AutoTokenizer.from_pretrained(
                    MODEL_ID, trust_remote_code=trust_remote_code
                )

        print(f"Loaded {{loaded_class}} from {{MODEL_ID}} on {{DEVICE}} (dtype={{DTYPE}})")
        '''
    ).strip()


def build_loader_cell(model_id: str) -> str:
    """Public adapter used by the Claro.AI web page."""
    if not isinstance(model_id, str) or not model_id.strip():
        raise ValueError("model_id is required")
    return _loader_cell(model_id.strip())


def build_cells(model_id: str, task: str):
    """Return two independent cells for non-browser callers.

    The task is only passed to the inference-template layer.  Importing the
    optional Transformers inspection modules is intentionally avoided here so
    the web server can generate cells without downloading a model.
    """
    from .task_templates import render_template

    task = (task or "").strip().lower()
    return build_loader_cell(model_id), (
        "# --- Cell 2: Inference template (auto-generated by Claro.AI) ---\n"
        f"# Task: {task or 'custom'}\n"
        "# Assumes the loader cell above has already run.\n\n"
        + render_template(task)
    )