from __future__ import annotations

from textwrap import dedent


def _loader_cell(model_id: str) -> str:
    """Build a task-independent loader.

    The generated code deliberately performs model inspection in the notebook
    runtime.  Inspecting a repo while the web page is generating a cell would
    make the page depend on server-side Transformers credentials and versions,
    and would also turn the selected task into an accidental loader hint.
    """
    return dedent(
        f'''
        # --- Cell 1: Model Loader (auto-generated by Claro.AI) ---
        # This cell only detects and loads the Hugging Face repo.
        import importlib
        import re
        import torch
        from transformers import AutoConfig

        MODEL_ID = {model_id!r}
        # Stable exports shared with the inference cell.  Keep these defined
        # even when a repo uses a different modality.  `preprocessor` is the
        # single canonical handle inference templates use; it is set to the
        # active tokenizer/processor/feature_extractor (or None) below so
        # templates never have to guess which one exists.
        model = None
        tokenizer = None
        processor = None
        feature_extractor = None
        preprocessor = None
        loaded_class = None

        DEVICE = torch.device(
            "cuda" if torch.cuda.is_available()
            else "mps" if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available()
            else "cpu"
        )
        DTYPE = torch.float16 if DEVICE.type == "cuda" else torch.float32
        DEVICE_MAP = "auto" if DEVICE.type == "cuda" else None

        def _has_diffusers_model_index():
            try:
                from huggingface_hub import hf_hub_download
                hf_hub_download(MODEL_ID, "model_index.json")
                return True
            except Exception:
                return False

        def _list_gguf_files():
            # Detect GGUF purely from repo file contents (extension), never from
            # the model family.  Returns the list of *.gguf files (case-insensitive).
            try:
                from huggingface_hub import HfApi
                files = HfApi().list_repo_files(MODEL_ID)
                return [f for f in files if f.lower().endswith(".gguf")]
            except Exception:
                return []

        _diffusers_repo = False
        _gguf_repo = False
        _gguf_files = _list_gguf_files()
        _config_requires_remote_code = False

        # Format detection runs BEFORE AutoConfig because GGUF repos do not
        # carry a Transformers config and crash there with "Unrecognized model".
        #   Diffusers -> model_index.json   (handled in the except below)
        #   GGUF      -> any *.gguf file     (guarded here, never calls AutoConfig)
        #   Transformers -> AutoConfig architecture resolver (unchanged)
        if _gguf_files:
            _gguf_repo = True
            config = type(
                "_GgufConfig",
                (),
                {{
                    "auto_map": {{}},
                    "architectures": [],
                    "model_type": "gguf",
                    "is_encoder_decoder": False,
                }},
            )()
        else:
            # AutoConfig is the source of truth.  The order below is intentional:
            # auto_map -> architectures -> model_type -> encoder/decoder structure.
            try:
                config = AutoConfig.from_pretrained(MODEL_ID, trust_remote_code=False)
            except Exception:
                try:
                    config = AutoConfig.from_pretrained(MODEL_ID, trust_remote_code=True)
                    _config_requires_remote_code = True
                except Exception:
                    # Pure Diffusers repos may not have a Transformers config at all.
                    # Check model_index.json only after AutoConfig has failed.
                    if not _has_diffusers_model_index():
                        raise
                    _diffusers_repo = True
                    config = type(
                        "_DiffusersConfig",
                        (),
                        {{
                            "auto_map": {{}},
                            "architectures": [],
                            "model_type": "",
                            "is_encoder_decoder": False,
                        }},
                    )()
        auto_map = getattr(config, "auto_map", None) or {{}}
        architectures = list(getattr(config, "architectures", None) or [])
        model_type = str(getattr(config, "model_type", "") or "").lower()
        is_encoder_decoder = bool(getattr(config, "is_encoder_decoder", False))
        def _architecture_requires_remote_code():
            if _config_requires_remote_code or not auto_map:
                return _config_requires_remote_code
            transformers = importlib.import_module("transformers")
            selected_key = next(
                (key for key in auto_map if key.startswith("AutoModelFor")),
                None,
            )
            mapped_targets = []
            for key, target in auto_map.items():
                if key.startswith("AutoModel") and (
                    selected_key is None or key == selected_key
                ):
                    mapped_targets.extend(
                        target if isinstance(target, (list, tuple)) else [target]
                    )
            if not mapped_targets:
                mapped_targets = list(auto_map.values())
            return any(
                not hasattr(transformers, str(target).rsplit(".", 1)[-1])
                for target in mapped_targets
            )

        trust_remote_code = _architecture_requires_remote_code()

        def _auto_class_from_map():
            for key in auto_map:
                if key.startswith("AutoModelFor"):
                    return key
            return None

        def _auto_class_from_architecture():
            # These are head/interface suffixes, not a model-family list.
            # New families with conventional HF architecture names work here
            # without adding their model_type to Claro.AI.
            suffixes = (
                ("ForQuestionAnswering", "AutoModelForQuestionAnswering"),
                ("ForSequenceClassification", "AutoModelForSequenceClassification"),
                ("ForTokenClassification", "AutoModelForTokenClassification"),
                ("ForMultipleChoice", "AutoModelForMultipleChoice"),
                ("ForMaskedLM", "AutoModelForMaskedLM"),
                ("ForCausalLM", "AutoModelForCausalLM"),
                ("ForImageTextToText", "AutoModelForImageTextToText"),
                ("ForVision2Seq", "AutoModelForVision2Seq"),
                ("ForSpeechSeq2Seq", "AutoModelForSpeechSeq2Seq"),
                ("ForAudioClassification", "AutoModelForAudioClassification"),
                ("ForImageClassification", "AutoModelForImageClassification"),
                ("ForObjectDetection", "AutoModelForObjectDetection"),
                ("ForSemanticSegmentation", "AutoModelForSemanticSegmentation"),
                ("ForDepthEstimation", "AutoModelForDepthEstimation"),
                ("ForCTC", "AutoModelForCTC"),
            )
            for architecture in architectures:
                for suffix, auto_class in suffixes:
                    if architecture.endswith(suffix):
                        return auto_class
            return None

        def _is_multimodal():
            metadata = " ".join(
                str(getattr(config, name, "") or "")
                for name in ("processor_class", "image_processor_type", "feature_extractor_type")
            ).lower()
            names = " ".join(architectures).lower() + " " + model_type
            return any(
                marker in metadata + " " + names
                for marker in ("vision", "image", "ocr", "document", "llava", "pix2struct")
            )

        def _is_audio():
            metadata = " ".join(
                str(getattr(config, name, "") or "")
                for name in ("processor_class", "feature_extractor_type")
            ).lower()
            names = " ".join(architectures).lower() + " " + model_type
            return any(marker in metadata + " " + names for marker in ("audio", "speech", "whisper"))

        def _auto_class_from_model_type():
            # model_type is a narrow fallback for families whose architecture
            # metadata is missing.  It is deliberately interface-oriented,
            # not a list of every model family on the Hub.
            return {{
                "whisper": "AutoModelForSpeechSeq2Seq",
                "wav2vec2": "AutoModelForCTC",
                "hubert": "AutoModelForCTC",
                "donut": "AutoModelForVision2Seq",
                "vision-encoder-decoder": "AutoModelForVision2Seq",
            }}.get(model_type)

        # Format dispatch.  GGUF is detected from repo file contents and never
        # run through Transformers.  Diffusers detection is repo-based.  All
        # other repos fall through to the unchanged Transformers resolver.
        if _gguf_repo:
            import os
            from llama_cpp import Llama

            def _pick_gguf(files):
                # Prefer a repo-declared default, then common *quantization*
                # conventions (file-format metadata, not model names).  If none
                # match, return None so the caller forces the user to choose.
                order = (
                    "default", "Q4_K_M", "q4_k_m", "Q5_K_M", "q5_k_m",
                    "Q4_K_S", "q4_k_s", "Q8_0", "q8_0", "Q6_K", "q6_k",
                    "Q4_0", "q4_0", "F16", "f16", "BF16", "bf16",
                )
                for tag in order:
                    for f in files:
                        if tag.lower() in f.lower():
                            return f
                if len(files) == 1:
                    return files[0]
                return None

            _gguf_files = sorted(_gguf_files, key=str.lower)
            GGUF_FILE = os.environ.get("CLARO_GGUF_FILE", "").strip() or None
            if GGUF_FILE is None:
                GGUF_FILE = _pick_gguf(_gguf_files)
            if GGUF_FILE is None:
                raise RuntimeError(
                    f"Multiple GGUF files found in {{MODEL_ID}}. Set the "
                    f"CLARO_GGUF_FILE env var to one of: "
                    + ", ".join(_gguf_files)
                )
            print(f"GGUF files available for {{MODEL_ID}}:")
            for f in _gguf_files:
                print(f"  {{'*' if f == GGUF_FILE else ' '}} {{f}}")
            print(f"Using: {{GGUF_FILE}}  (override with env CLARO_GGUF_FILE)")

            n_ctx = int(os.environ.get("CLARO_GGUF_NCTX", "4096"))
            _llm_kwargs = {{"n_ctx": n_ctx}}
            if DEVICE.type != "cpu":
                _llm_kwargs["n_gpu_layers"] = int(
                    os.environ.get("CLARO_GGUF_NGPULAYERS", "-1")
                )

            try:
                _llm = Llama.from_pretrained(MODEL_ID, filename=GGUF_FILE, **_llm_kwargs)
            except Exception:
                # Older llama-cpp-python builds need a local path.
                from huggingface_hub import hf_hub_download
                _path = hf_hub_download(MODEL_ID, GGUF_FILE)
                _llm = Llama(_path, **_llm_kwargs)

            def _to_id_list(x):
                if hasattr(x, "tolist"):
                    return x.tolist()
                return list(x)

            class _GgufPreprocessor:
                # Exposes the same surface the inference templates rely on:
                # __call__(prompt, return_tensors=...) -> {{input_ids, ...}}
                # plus .decode / .eos_token_id.
                def __init__(self, llm):
                    self._llm = llm

                @property
                def eos_token_id(self):
                    try:
                        return self._llm.token_eos()
                    except Exception:
                        return None

                def __call__(self, prompt, return_tensors=None, **kw):
                    if not isinstance(prompt, str):
                        raise TypeError(
                            "GGUF preprocessor expects a str prompt; "
                            "batch/multimodal inputs are not supported."
                        )
                    ids = self._llm.tokenize(
                        prompt.encode("utf-8"), add_bos=True, special=True
                    )
                    t = torch.tensor([ids], dtype=torch.long)
                    return {{"input_ids": t, "attention_mask": torch.ones_like(t)}}

                def decode(self, token_ids, skip_special_tokens=True):
                    flat = _to_id_list(token_ids)
                    if flat and isinstance(flat[0], list):
                        flat = flat[0]
                    return self._llm.detokenize(flat).decode("utf-8", errors="ignore")

            class _GgufModel:
                # Wraps llama-cpp-python so the existing text-generation
                # template (model.generate(**inputs) + preprocessor.decode)
                # works unchanged.  GGUF is not assumed to be Llama-based;
                # llama.cpp reads the architecture from the GGUF metadata.
                def __init__(self, llm):
                    self._llm = llm
                    self.device = torch.device("cpu")
                    self.config = type(
                        "_GgufCfg",
                        (),
                        {{"is_encoder_decoder": False, "model_type": "gguf"}},
                    )()

                def eval(self):
                    return self

                def to(self, *a, **k):
                    return self

                def generate(self, input_ids=None, attention_mask=None,
                             max_new_tokens=128, do_sample=False,
                             temperature=0.7, top_p=0.9, top_k=50,
                             repetition_penalty=1.1, pad_token_id=None, **kw):
                    ids = _to_id_list(input_ids)[0]
                    prompt = self._llm.detokenize(ids).decode("utf-8", errors="ignore")
                    args = {{"max_tokens": int(max_new_tokens)}}
                    if do_sample:
                        if temperature is not None:
                            args["temperature"] = float(temperature)
                        if top_p is not None:
                            args["top_p"] = float(top_p)
                        if top_k is not None and int(top_k) > 0:
                            args["top_k"] = int(top_k)
                        if repetition_penalty and float(repetition_penalty) != 1.0:
                            args["repeat_penalty"] = float(repetition_penalty)
                    resp = self._llm.create_completion(prompt, **args)
                    new_text = resp["choices"][0]["text"]
                    new_ids = self._llm.tokenize(
                        new_text.encode("utf-8"), add_bos=False, special=False
                    )
                    full = ids + new_ids
                    return [torch.tensor([full], dtype=torch.long)]

            model = _GgufModel(_llm)
            preprocessor = _GgufPreprocessor(_llm)
            tokenizer = None
            processor = None
            feature_extractor = None
            loaded_class = "GGUF (llama-cpp-python)"

        elif _diffusers_repo:
            from diffusers import DiffusionPipeline

            pipe_kwargs = {{"dtype": DTYPE}} if DEVICE.type == "cuda" else {{}}
            pipe = DiffusionPipeline.from_pretrained(MODEL_ID, **pipe_kwargs)
            pipe = pipe.to(DEVICE)
            model = None
            tokenizer = None
            processor = None
            feature_extractor = None
            preprocessor = None
            loaded_class = "DiffusionPipeline"
        else:
            mapped_class = _auto_class_from_map()
            architecture_class = _auto_class_from_architecture()
            model_type_class = _auto_class_from_model_type()
            loaded_class = mapped_class or architecture_class or model_type_class

            known_text_decoder_types = {{
                "llama", "qwen", "qwen2", "gemma", "gemma2", "mistral",
                "mixtral", "deepseek", "phi", "phi3", "gpt2", "gpt_neox",
                "falcon", "bloom", "mamba", "starcoder",
            }}
            if not loaded_class:
                if is_encoder_decoder:
                    loaded_class = "AutoModelForSeq2SeqLM"
                elif _is_multimodal():
                    loaded_class = "AutoModelForVision2Seq"
                elif model_type in known_text_decoder_types:
                    loaded_class = "AutoModelForCausalLM"
                else:
                    loaded_class = "AutoModel"
                    print(
                        f"Warning: unknown architecture for {{MODEL_ID}}; "
                        "using AutoModel."
                    )
            elif loaded_class == "AutoModelForConditionalGeneration":
                loaded_class = (
                    "AutoModelForVision2Seq" if _is_multimodal()
                    else "AutoModelForSeq2SeqLM" if is_encoder_decoder
                    else "AutoModelForCausalLM"
                )

            transformers = importlib.import_module("transformers")
            ModelClass = getattr(transformers, loaded_class, None)
            if ModelClass is None and loaded_class == "AutoModelForImageTextToText":
                ModelClass = getattr(transformers, "AutoModelForVision2Seq")
                loaded_class = "AutoModelForVision2Seq"
            if ModelClass is None:
                raise RuntimeError(
                    f"Transformers does not provide {{loaded_class}} for {{MODEL_ID}}. "
                    f"architectures={{architectures!r}}, model_type={{model_type!r}}"
                )

            model_kwargs = {{"trust_remote_code": trust_remote_code}}
            if DEVICE.type == "cuda":
                model_kwargs.update(dtype=DTYPE, device_map=DEVICE_MAP)
            model = ModelClass.from_pretrained(MODEL_ID, **model_kwargs)
            if DEVICE_MAP is None:
                model = model.to(DEVICE)
            model.eval()

            # Processor choice comes from repo/config metadata, never from the
            # selected pipeline task.
            tokenizer = None
            processor = None
            feature_extractor = None
            if any(
                marker in loaded_class
                for marker in (
                    "ImageClassification",
                    "ObjectDetection",
                    "SemanticSegmentation",
                    "DepthEstimation",
                )
            ):
                from transformers import AutoImageProcessor
                processor = AutoImageProcessor.from_pretrained(
                    MODEL_ID, trust_remote_code=trust_remote_code
                )
            elif _is_multimodal() or "Vision2Seq" in loaded_class or "ImageTextToText" in loaded_class:
                from transformers import AutoProcessor
                processor = AutoProcessor.from_pretrained(
                    MODEL_ID, trust_remote_code=trust_remote_code
                )
            elif _is_audio() and "AudioClassification" in loaded_class:
                from transformers import AutoFeatureExtractor
                feature_extractor = AutoFeatureExtractor.from_pretrained(
                    MODEL_ID, trust_remote_code=trust_remote_code
                )
                processor = feature_extractor
            elif _is_audio() or "SpeechSeq2Seq" in loaded_class or "CTC" in loaded_class:
                from transformers import AutoProcessor
                processor = AutoProcessor.from_pretrained(
                    MODEL_ID, trust_remote_code=trust_remote_code
                )
            else:
                from transformers import AutoTokenizer
                tokenizer = AutoTokenizer.from_pretrained(
                    MODEL_ID, trust_remote_code=trust_remote_code
                )

            # Single canonical handle the inference templates rely on.  The
            # logic above already decided the modality; templates must never
            # re-guess between tokenizer / processor / feature_extractor.
            preprocessor = tokenizer or processor or feature_extractor

        print(f"Loaded {{loaded_class}} from {{MODEL_ID}} on {{DEVICE}} (dtype={{DTYPE}})")
        '''
    ).strip()


def build_loader_cell(model_id: str) -> str:
    """Public adapter used by the Claro.AI web page."""
    if not isinstance(model_id, str) or not model_id.strip():
        raise ValueError("model_id is required")
    return _loader_cell(model_id.strip())


def build_cells(model_id: str, task: str):
    """Return two independent cells for non-browser callers.

    The task is only passed to the inference-template layer.  Importing the
    optional Transformers inspection modules is intentionally avoided here so
    the web server can generate cells without downloading a model.
    """
    from .task_templates import render_template

    task = (task or "").strip().lower()
    return build_loader_cell(model_id), (
        "# --- Cell 2: Inference template (auto-generated by Claro.AI) ---\n"
        f"# Task: {task or 'custom'}\n"
        "# Assumes the loader cell above has already run.\n\n"
        + render_template(task)
    )